### ISSUE TITLE
Exception Occurred

### ISSUE THREAD

**Issue by miekion** [Vxider/NiuDataWidget#1]
系统版本：ios15.0.1
Scriptable版本：1.6.11
就改了个username、password、sn
就弹出这个错误了，麻烦大佬看看
![wecom-temp-4e633ccd8e12defed33e86bcd53a111e](https://user-images.githubusercontent.com/13217017/136494995-4fdfc9cd-1955-4d56-8db8-e447e6a2c709.jpg)

**Comment by miekion** [comment]
line on 613
![image](https://user-images.githubusercontent.com/13217017/136495280-13f0760b-c3d5-4813-a451-5b6710767998.png)

**Comment by Vxider** [comment]
613行无法看出错误出在哪里，可以调试下`loadNiuData`函数，分别打印变量`infoJson`,`lastTrackJSON`,`scooterDetailJSON`，看看信息是否获取正确

**Comment by fzbxb** [comment]
同样的问题，有解决了吗

**Comment by Vxider** [comment]
> 同样的问题，有解决了吗

由于不同小牛车型，不同中控版本，可能拿到的数据格式不同，我自己只有一辆v35s的M+，没法调试其他车型。所以还需要将这几个变量打印出来`infoJson`,`lastTrackJSON`,`scooterDetailJSON`才能想办法解决。

**Comment by fzbxb** [comment]
小白表示不知道怎么调用和打印，有没有教程额。。（可怜）

**Comment by zhuguanan** [comment]
同样问题

**Comment by Vxider** [comment]
目前我自己的账号目前是可以正常使用的，如果有人愿意提供自己的账号帮助调试，我愿意尝试修复此问题

**Comment by shmilyshirley** [comment]
> 

大佬 我也是这个报错，我愿提供账号密码  用于调试，我该如何将帐密发给你呢？

**Comment by Vxider** [comment]
> > 
> 
> 大佬 我也是这个报错，我愿提供账号密码 用于调试，我该如何将帐密发给你呢？

@shmilyshirley 您可以改一个临时密码，将用户名密码以及设备SN发送至lb@vxider.com，我调试后您再把密码改回来

**Comment by Vxider** [comment]
我更新了一版代码，出问题的朋友可以试试，测试前可尝试删除`iCloud/Scriptable/niu_data`文件夹

**Comment by zhuguanan** [comment]
运行脚本，报错：NETWORK EXCEPTION

**Comment by Vxider** [comment]
@shmilyshirley 代码您现在可以正常使用吗？

**Comment by shmilyshirley** [comment]
已经可以使用了，谢谢你的帮助！


| |
shmilyshirley
|
|
***@***.***
|
签名由网易邮箱大师定制


On 11/30/2021 ***@***.***> wrote：

@shmilyshirley 代码您现在可以正常使用吗？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhuguanan** [comment]
密码MD5加密，是16位还是32位的，是大写，还是小写

**Comment by Vxider** [comment]
> 

@zhuguanan 32位小写

**Comment by zhuguanan** [comment]
好的，我再试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vxider/NiuDataWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vxider/NiuDataWidget] Exception Occurred (#1)





   
@zhuguanan 32位小写
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vxider** [comment]
> 好的，我再试试

新版代码可以显示错误信息，可以更新试下

**Comment by zhuguanan** [comment]
可以了，感谢大神指点，完美！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vxider/NiuDataWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vxider/NiuDataWidget] Exception Occurred (#1)





 
Reopened #1.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Vxider** [comment]
新增车辆遥控功能，欢迎大家试用

**Comment by wuzhaolin** [comment]
![b1d88cca5e7ea4bd847985eb261cc55](https://user-images.githubusercontent.com/19644487/144989734-35846f71-63cd-4969-a546-ba648e3a554b.jpg)
执行时出现此报错，大佬有没试过

**Comment by zhuguanan** [comment]
你问一下作者，我这边没有遇到这个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vxider/NiuDataWidget"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月7日(星期二) 下午4:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vxider/NiuDataWidget] Exception Occurred (#1)





 

 执行时出现此报错，大佬有没试过
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wuzhaolin** [comment]
> 新增车辆遥控功能，欢迎大家试用
![b1d88cca5e7ea4bd847985eb261cc55](https://user-images.githubusercontent.com/19644487/144990463-72d2fd74-9a17-4439-ae84-89cee65a8e02.jpg)

执行时出现此报错，大佬有没试过

**Comment by Vxider** [comment]
> 执行时出现此报错，大佬有没试过

换个网络环境试试看是否为网络问题，如果不是，可以打印错误信息看看

**Comment by wuzhaolin** [comment]
> 

后来又正常了，求 教如何打印

**Comment by Vxider** [comment]
> 后来又正常了，求 教如何打印

应该是网络问题，图片会缓存，下载一次后就不会再次重新下载了

**Comment by YinHang119** [comment]
> 新增车辆遥控功能，欢迎大家试用

状态小组件已设置成功，谢谢作者！ 麻烦问一下，这个遥控的快捷指令，怎么使用呢？手机已添加，点击运行后手机振动。该如何设置呢？谢谢

**Comment by l383342232** [comment]
大佬，app电池信息里的放电图和循环次数等信息可以调出来到这个界面嘛

**Comment by l383342232** [comment]
> > 新增车辆遥控功能，欢迎大家试用
> 
> 状态小组件已设置成功，谢谢作者！ 麻烦问一下，这个遥控的快捷指令，怎么使用呢？手机已添加，点击运行后手机振动。该如何设置呢？谢谢

快捷指令里改名字，改成你script里的js文件名

**Comment by Vxider** [comment]
> 大佬，app电池信息里的放电图和循环次数等信息可以调出来到这个界面嘛

放电图没有研究过，循环次数还是比较容易加的，只是小组件里没有一个合理的位置

**Comment by l383342232** [comment]
> 

就是类似apple watch在手机小组件能看心电图，或者训练强度图，这种。 求问循环次数咋加呀

**Comment by Composure17** [comment]
大佬 mapkey如果要用高德的key应该怎么设置 还要改什么变量的设置吗

**Comment by Vxider** [comment]
> 大佬 mapkey如果要用高德的key应该怎么设置 还要改什么变量的设置吗

@Composure17 修改这段就行

https://github.com/Vxider/NiuDataWidget/blob/ec759652ebb6e47e71fbd6f3d30fc0cd055ad84c/NiuDataWidget.js#L275-L281

**Comment by Composure17** [comment]
如果我想他一直是黑色的可以吗 @Vxider

**Comment by Composure17** [comment]
如果我想他一直是黑色的可以吗 @Vxider 
我感觉那个数据板是不是拿你的代码了

**Comment by Composure17** [comment]
如果我想他一直是黑色的可以吗 @Vxider

**Comment by Vxider** [comment]
> 如果我想他一直是黑色的可以吗 @Vxider

@Composure17 可以看下地图API，URL参数里是否能强制黑色。

**Comment by Composure17** [comment]
啊哈哈哈我表达错了 就是is_dark_mode_working这个不是跟随系统变色嘛 有没有能一直保持黑色的

**Comment by Composure17** [comment]
地图那儿我在看

**Comment by Vxider** [comment]
> 啊哈哈哈我表达错了 就是is_dark_mode_working这个不是跟随系统变色嘛 有没有能一直保持黑色的

https://github.com/Vxider/NiuDataWidget/blob/ec759652ebb6e47e71fbd6f3d30fc0cd055ad84c/NiuDataWidget.js#L48-L51

这个地方改成

```
return true;
```

就好了

**Comment by Composure17** [comment]
谢谢大佬

**Comment by Composure17** [comment]
大佬 他那个请求battery_info是一个什么值 登陆返回的token吗

**Comment by Vxider** [comment]
@Composure17 `battery_info`应该是电池信息，另外主题不相关问题建议单独开一个issue，以免“打扰”到其他参与者

**Comment by yaojiajian** [comment]
大佬，我的地图一直不显示出来怎么办呀，注册地图API key也注册失败了
